spring:
  application:
    name: customer-transaction
  datasource:
    url: jdbc:postgresql://localhost:5432/customer-transacation
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml

  profiles:
    active: dev  # Activates the 'dev' profile
